# Generated by Django 4.0 on 2021-12-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_link_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link_codigo',
            new_name='linkCodigo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='link_demo',
            new_name='linkDemo',
        ),
    ]
