# Generated by Django 4.0 on 2021-12-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_link_codigo_project_linkcodigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='linkCodigo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='linkDemo',
        ),
    ]
