# Generated by Django 4.0 on 2021-12-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_linkcodigo_remove_project_linkdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linkCodigo',
            field=models.URLField(blank=True, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='project',
            name='linkDemo',
            field=models.URLField(blank=True, null=True, verbose_name='Demo'),
        ),
    ]
