# Generated by Django 4.0 on 2021-12-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_linkcodigo_project_linkdemo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='linkDemo',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='linkCodigo',
        ),
    ]
