# Generated by Django 4.0 on 2021-12-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_linkdemo_project_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='link_demo',
        ),
        migrations.AddField(
            model_name='project',
            name='link_codigo',
            field=models.URLField(blank=True, null=True, verbose_name='Código'),
        ),
    ]
